
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JOSE
 */
public class Imprimele extends javax.swing.JFrame implements Printable
{

	/**
	 * Creates new form Imprimele
	 */
	public Imprimele()
	{
		initComponents();


		/*txtFolio.setText( folio );
		txtCliente.setText( nombre );
		txtHabitacion.setText( numero );
		txtFechaEntrada.setText( fechaEntrada );
		txtFechaSalida.setText( fechaSalida );
		txtTotal.setText( total );*/
	}

	public int print( Graphics graphics , PageFormat pageFormat , int pageIndex ) throws PrinterException
	{

		if ( pageIndex > 0 )
		{
			/* We have only one page, and 'page' is zero-based */
			return NO_SUCH_PAGE;
		}
		Graphics2D g2d = ( Graphics2D ) graphics;
		g2d.translate( pageFormat.getImageableX() , pageFormat.getImageableY() );

		jPanel1.printAll( graphics );

		return PAGE_EXISTS;

	}

	private void imprimir()
	{
		try
		{
			PrinterJob job = PrinterJob.getPrinterJob();
			job.setPrintable( this );
			job.printDialog();
			job.print();
		}
		catch ( PrinterException ex )
		{
			Logger.getLogger( Imprimele.class.getName() ).log( Level.SEVERE , null , ex );
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHabitacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comprobante");
        setMinimumSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/hotel-3.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 180, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel\"La Primavera\"");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 150, 357, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 320, 136, 28);

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCliente);
        txtCliente.setBounds(200, 320, 280, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Folio:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 280, 68, 20);

        txtFolio.setEditable(false);
        txtFolio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFolio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtFolio);
        txtFolio.setBounds(200, 270, 125, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Numero de habitacion:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 370, 179, 22);

        txtHabitacion.setEditable(false);
        txtHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHabitacion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtHabitacion);
        txtHabitacion.setBounds(200, 360, 83, 37);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha Entrada:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 410, 150, 30);

        txtFechaEntrada.setEditable(false);
        txtFechaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFechaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaEntrada.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFechaEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaEntrada);
        txtFechaEntrada.setBounds(200, 410, 137, 38);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fecha Salida:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 460, 120, 35);

        txtFechaSalida.setEditable(false);
        txtFechaSalida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFechaSalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFechaSalida);
        txtFechaSalida.setBounds(200, 460, 137, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 530, 73, 22);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(200, 530, 110, 32);

        jLabel9.setText("Telefono:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 200, 70, 16);

        jLabel10.setText("(407) 996-0865 ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 200, 130, 16);

        jLabel11.setText("Av.Zapata  #418");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 220, 140, 16);

        jLabel12.setText("Email:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(120, 240, 38, 16);

        jLabel13.setText("hotel@gmail.com");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(170, 240, 110, 16);

        jLabel14.setText("¡Gracias por su preferencia!");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(200, 620, 190, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtHabitacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtHabitacionActionPerformed
    {//GEN-HEADEREND:event_txtHabitacionActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtHabitacionActionPerformed

    private void txtFechaEntradaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFechaEntradaActionPerformed
    {//GEN-HEADEREND:event_txtFechaEntradaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEntradaActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel14MouseClicked
    {//GEN-HEADEREND:event_jLabel14MouseClicked
		imprimir();
    }//GEN-LAST:event_jLabel14MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
			{
				if ( "Nimbus".equals( info.getName() ) )
				{
					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
					break;
				}
			}
		}
		catch ( ClassNotFoundException ex )
		{
			java.util.logging.Logger.getLogger( Imprimele.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( InstantiationException ex )
		{
			java.util.logging.Logger.getLogger( Imprimele.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( IllegalAccessException ex )
		{
			java.util.logging.Logger.getLogger( Imprimele.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( javax.swing.UnsupportedLookAndFeelException ex )
		{
			java.util.logging.Logger.getLogger( Imprimele.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				new Imprimele().setVisible( true );
			}

		} );
	}

	public String getFolio()
	{
		return folio;
	}

	public void setFolio( String folio )
	{
		this.folio = folio;
	}

	public String getNombre()
	{
		return nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

	public String getNumero()
	{
		return numero;
	}

	public void setNumero( String numero )
	{
		this.numero = numero;
	}

	public String getFechaEntrada()
	{
		return fechaEntrada;
	}

	public void setFechaEntrada( String fechaEntrada )
	{
		this.fechaEntrada = fechaEntrada;
	}

	public String getFechaSalida()
	{
		return fechaSalida;
	}

	public void setFechaSalida( String fechaSalida )
	{
		this.fechaSalida = fechaSalida;
	}

	public String getTotal()
	{
		return total;
	}

	public void setTotal( String total )
	{
		this.total = total;
	}

	String folio, nombre, numero, fechaEntrada, fechaSalida, total;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JTextField txtFechaEntrada;
    public javax.swing.JTextField txtFechaSalida;
    public javax.swing.JTextField txtFolio;
    public javax.swing.JTextField txtHabitacion;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
