
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JOSE
 */
public class Inicio extends javax.swing.JFrame
{

	/**
	 * Creates new form Inicio
	 */
	public Inicio()
	{
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarHabitacion = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReservacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOTEL \"  La Primavera \"");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 470, 110));

        btnAgregarHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/habitacion.png"))); // NOI18N
        btnAgregarHabitacion.setText("Agregar Habitacion");
        btnAgregarHabitacion.setMaximumSize(new java.awt.Dimension(177, 76));
        btnAgregarHabitacion.setMinimumSize(new java.awt.Dimension(177, 76));
        btnAgregarHabitacion.setPreferredSize(new java.awt.Dimension(177, 76));
        btnAgregarHabitacion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarHabitacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 270, 90));

        btnEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/colaboracion.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 240, 90));

        btnHistorial.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/historial-medico.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 260, 90));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/cerrar-2.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 710, 90, 50));

        btnReservacion.setBackground(new java.awt.Color(255, 255, 255));
        btnReservacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/online-booking (1).png"))); // NOI18N
        btnReservacion.setText("Reservacion");
        btnReservacion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReservacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 240, 90));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel6.setText("Avenida Zapata #418");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, -1, -1));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel5.setText("Telefono: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, -1, -1));

        lblNombre.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        lblNombre.setText("Hotel\"La Primavera\"");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 230, 30));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel7.setText("E-mail:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        lblTelefono.setText("324-24-1-8795");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/hotel-3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 270, 190));

        lblEmail.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        lblEmail.setText("hotel@gmail.com");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/inicio.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReservacionActionPerformed
    {//GEN-HEADEREND:event_btnReservacionActionPerformed
		VentanaReservacion reserva = new VentanaReservacion();
		reserva.setVisible( true );
		this.dispose();

    }//GEN-LAST:event_btnReservacionActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHistorialActionPerformed
    {//GEN-HEADEREND:event_btnHistorialActionPerformed
		VentanaHistorial historial = new VentanaHistorial();
		historial.setVisible( true );
		this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEmpleadosActionPerformed
    {//GEN-HEADEREND:event_btnEmpleadosActionPerformed
		VentanaEmpleado empleado = new VentanaEmpleado();
		empleado.setVisible( true );
		this.dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnAgregarHabitacionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarHabitacionActionPerformed
    {//GEN-HEADEREND:event_btnAgregarHabitacionActionPerformed
		VentanaHabitaciones habitaciones = new VentanaHabitaciones();
		habitaciones.setVisible( true );
		this.dispose();
    }//GEN-LAST:event_btnAgregarHabitacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
		if ( javax.swing.JOptionPane.showConfirmDialog( this , "¿Desea Salir?" , "" , JOptionPane.YES_NO_OPTION ) == 0 )
			System.exit( 0 );
    }//GEN-LAST:event_btnSalirActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
			{
				if ( "Nimbus".equals( info.getName() ) )
				{
					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
					break;
				}
			}
		}
		catch ( ClassNotFoundException ex )
		{
			java.util.logging.Logger.getLogger( Inicio.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( InstantiationException ex )
		{
			java.util.logging.Logger.getLogger( Inicio.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( IllegalAccessException ex )
		{
			java.util.logging.Logger.getLogger( Inicio.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( javax.swing.UnsupportedLookAndFeelException ex )
		{
			java.util.logging.Logger.getLogger( Inicio.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				new Inicio().setVisible( true );
			}

		} );
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarHabitacion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnReservacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables

}
