
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Casillas
 */
public class VentanaHistorial extends javax.swing.JFrame
{

	/**
	 * Creates new form VentanaHistorial
	 */
	public VentanaHistorial()
	{
		initComponents();
		m = ( DefaultTableModel ) tblHistorialReservación.getModel();
		cargarTablaDesdeBD();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorialReservación = new javax.swing.JTable();
        btnInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        txtHuesped = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnRegistrarSalida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtNumeroHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1400, 30));

        lbTitulo.setFont(new java.awt.Font("Times", 1, 24)); // NOI18N
        lbTitulo.setText("HISTORIAL");
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 132, -1, -1));

        tblHistorialReservación.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Folio", "Nombre", "Edad", "Telefono", "Entrada", "Salida", "Habitacion", "Total"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblHistorialReservación.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblHistorialReservaciónMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHistorialReservación);
        if (tblHistorialReservación.getColumnModel().getColumnCount() > 0)
        {
            tblHistorialReservación.getColumnModel().getColumn(0).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(0).setPreferredWidth(18);
            tblHistorialReservación.getColumnModel().getColumn(1).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(2).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(2).setPreferredWidth(18);
            tblHistorialReservación.getColumnModel().getColumn(3).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(4).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(5).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(6).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(6).setPreferredWidth(60);
            tblHistorialReservación.getColumnModel().getColumn(7).setResizable(false);
            tblHistorialReservación.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 650, 470));

        btnInicio.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/boton-de-inicio.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 120, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Edad del huésped:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 150, 150, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Télefono:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 200, 100, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Folio:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 40, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nombre del huésped:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 100, 170, 22);

        txtFolio.setEditable(false);
        jPanel1.add(txtFolio);
        txtFolio.setBounds(250, 40, 300, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fecha de Entrada: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 250, 150, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha de Salida:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 300, 140, 22);

        txtFechaEntrada.setEditable(false);
        jPanel1.add(txtFechaEntrada);
        txtFechaEntrada.setBounds(250, 250, 231, 28);

        txtHuesped.setEditable(false);
        jPanel1.add(txtHuesped);
        txtHuesped.setBounds(260, 100, 130, 29);

        txtEdad.setEditable(false);
        jPanel1.add(txtEdad);
        txtEdad.setBounds(260, 150, 190, 31);

        txtTelefono.setEditable(false);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(250, 200, 310, 29);

        txtFechaSalida.setEditable(false);
        jPanel1.add(txtFechaSalida);
        txtFechaSalida.setBounds(250, 300, 231, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Total de Estadía:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 390, 150, 22);

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal);
        txtTotal.setBounds(250, 390, 120, 30);

        btnRegistrarSalida.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegistrarSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/salida.png"))); // NOI18N
        btnRegistrarSalida.setText("Registrar Salida ");
        btnRegistrarSalida.setEnabled(false);
        btnRegistrarSalida.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarSalida);
        btnRegistrarSalida.setBounds(380, 430, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Número de Habitacion: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 350, 190, 20);

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/cerrar-2.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(60, 430, 150, 44);
        jPanel1.add(txtNumeroHabitacion);
        txtNumeroHabitacion.setBounds(250, 350, 120, 26);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 640, 500));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Detalles de la Reservación");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/imprimir_1.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 130, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1400, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 50));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/lupa-de-busqueda.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/hotel-3.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(0, 0, 155, 120);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1390, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInicioActionPerformed
    {//GEN-HEADEREND:event_btnInicioActionPerformed
		Inicio inicio = new Inicio();
		inicio.setVisible( true );
		this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void tblHistorialReservaciónMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblHistorialReservaciónMouseClicked
    {//GEN-HEADEREND:event_tblHistorialReservaciónMouseClicked

		txtFolio.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 0 ).toString() );
		txtHuesped.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 1 ).toString() );
		txtEdad.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 2 ).toString() );
		txtTelefono.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 3 ).toString() );
		txtFechaEntrada.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 4 ).toString() );
		txtFechaSalida.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 5 ).toString() );
		txtNumeroHabitacion.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 6 ).toString() );
		txtTotal.setText( tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 7 ).toString() );

		btnRegistrarSalida.setEnabled( true );
    }//GEN-LAST:event_tblHistorialReservaciónMouseClicked

	private void limpirar()
	{
		txtFolio.setText( "" );
		txtHuesped.setText( "" );
		txtEdad.setText( "" );
		txtTelefono.setText( "" );
		txtFechaEntrada.setText( "" );
		txtFechaSalida.setText( "" );
		txtNumeroHabitacion.setText( "" );
		txtTotal.setText( "" );

	}

    private void btnRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarSalidaActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarSalidaActionPerformed
		if ( javax.swing.JOptionPane.showConfirmDialog( this , "¿Desea registrar la salida de la habitacion " + tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 6 ).toString() + "?" , "Registrar Salida" , JOptionPane.YES_NO_OPTION ) == 0 )
		{
			cambiarDisponibilidad();

			Imprimele imprimir = new Imprimele();
			imprimir.setVisible( true );
			imprimir.txtFolio.setText( this.txtFolio.getText() );
			imprimir.txtCliente.setText( this.txtHuesped.getText() );
			imprimir.txtHabitacion.setText( this.txtNumeroHabitacion.getText() );
			imprimir.txtFechaEntrada.setText( this.txtFechaEntrada.getText() );
			imprimir.txtFechaSalida.setText( this.txtFechaSalida.getText() );
			imprimir.txtTotal.setText( "$" + this.txtTotal.getText() + ".00" );

			//showMessageDialog( this , folio );
			limpirar();

			btnRegistrarSalida.setEnabled( false );

		}
    }//GEN-LAST:event_btnRegistrarSalidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
		try
		{
			MessageFormat headerFormat = new MessageFormat( "Historial de reservaciones" );
			MessageFormat footerFormat = new MessageFormat( "" );

			tblHistorialReservación.print( JTable.PrintMode.NORMAL , headerFormat , footerFormat );
		}
		catch ( PrinterException e )
		{

		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
		String cad = JOptionPane.showInputDialog( "Ingrese el nombre del cliente" );
		m.setRowCount( 0 );
		Buscar( cad );

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
		limpirar();
		m.setRowCount( 0 );
		cargarTablaDesdeBD();
    }//GEN-LAST:event_btnCancelarActionPerformed

	private void cambiarDisponibilidad()
	{

		Connection c = conexionBD();
		String insert = "update Habitaciones set disponibilidad=? where numero=" + tblHistorialReservación.getValueAt( tblHistorialReservación.getSelectedRow() , 6 ).toString();

		try
		{
			Statement stmt = c.createStatement();
			PreparedStatement ps;

			ps = c.prepareStatement( insert );
			ps.setString( 1 , "Disponible" );

			ps.executeUpdate();

			c.close();
		}
		catch ( SQLException ex )
		{
			Logger.getLogger( VentanaReservacion.class.getName() ).log( Level.SEVERE , null , ex );

		}

	}

	private Connection conexionBD()
	{
		String url = "jdbc:mysql://localhost:3306/Hotel";
		System.out.println( "Conectando..." );

		Connection connection = null;

		try
		{
			connection = DriverManager.getConnection( url , "root" , "werick" );

			System.out.println( "Conectado a la base de datos " + "Hotel" + " !!" );

		}
		catch ( SQLException e )
		{
			System.out.println( "No se pudo conectar a la base de datos " + "Hotel" );
			System.out.println( e.getMessage() );
		}

		return connection;
	}

	private void cargarTablaDesdeBD()
	{
		String q = "select * from Reservaciones;";

		Connection c = conexionBD();

		String prueba = "";

		int folio;

		String nombre;
		int edad;
		String telefono;
		String fechaEntrada;
		String fechaSalida;
		int numHabitacion;
		int total;

		try
		{

			Statement stmt = c.createStatement();
			stmt.execute( q );
			ResultSet rs = stmt.getResultSet();
			if ( rs != null )
			{
				while ( rs.next() )
				{
					folio = rs.getInt( "folioReserva" );
					nombre = rs.getString( "nombre" );
					edad = rs.getInt( "edad" );
					telefono = rs.getString( "telefono" );
					fechaEntrada = rs.getString( "fechaEntrada" );
					fechaSalida = rs.getString( "fechaSalida" );
					numHabitacion = rs.getInt( "numeroHabitacion" );
					total = rs.getInt( "costoTotal" );

					/*prueba += "(" + strNumero + "," + strTipo + "," + strDisponibilidad + ","
						+ strPrecio + ")\n";*/
					agregar_a_tabla( folio , nombre , edad , telefono , fechaEntrada , fechaSalida , numHabitacion , total );
				}
			}

			c.close(); // no dejar la conexión abierta

		}
		catch ( SQLException e )
		{
			System.out.println( "Error al cargar datos de la tabla Reservaciones" );
			System.out.println( e.getMessage() );
		}

		System.out.println( q + "\n" + prueba );

	}

	private void Buscar( String cad )
	{
		String q = "select * from Reservaciones where nombre='" + cad + "';";

		Connection c = conexionBD();

		String prueba = "";

		int folio;

		String nombre;
		int edad;
		String telefono;
		String fechaEntrada;
		String fechaSalida;
		int numHabitacion;
		int total;

		try
		{

			Statement stmt = c.createStatement();
			stmt.execute( q );
			ResultSet rs = stmt.getResultSet();
			if ( rs != null )
			{
				while ( rs.next() )
				{
					folio = rs.getInt( "folioReserva" );
					nombre = rs.getString( "nombre" );
					edad = rs.getInt( "edad" );
					telefono = rs.getString( "telefono" );
					fechaEntrada = rs.getString( "fechaEntrada" );
					fechaSalida = rs.getString( "fechaSalida" );
					numHabitacion = rs.getInt( "numeroHabitacion" );
					total = rs.getInt( "costoTotal" );

					/*prueba += "(" + strNumero + "," + strTipo + "," + strDisponibilidad + ","
						+ strPrecio + ")\n";*/
					agregar_a_tabla( folio , nombre , edad , telefono , fechaEntrada , fechaSalida , numHabitacion , total );
				}
			}

			c.close(); // no dejar la conexión abierta

		}
		catch ( SQLException e )
		{
			System.out.println( "Error al cargar datos de la tabla Reservaciones" );
			System.out.println( e.getMessage() );
		}

		System.out.println( q + "\n" + prueba );

	}

	private void agregar_a_tabla( int s1 , String s2 , int s3 , String s4 , String s5 , String s6 , int s7 , int s8 )
	{

		// aquí agregar las cadenas a la tabla
		Object O[] = new Object[ 8 ];
		O[ 0 ] = s1;
		O[ 1 ] = s2;
		O[ 2 ] = s3;
		O[ 3 ] = s4;
		O[ 4 ] = s5;
		O[ 5 ] = s6;
		O[ 6 ] = s7;
		O[ 7 ] = s8;
		m.addRow( O );

	}

	public void obtenerDatos()
	{

		Imprimele imprimir = new Imprimele();
		imprimir.setVisible( true );
		imprimir.txtFolio.setText( this.txtFolio.getText() );
		imprimir.txtCliente.setText( this.txtHuesped.getText() );

		/*folio = txtFolio.getText();
		numero = txtNumeroHabitacion.getText();
		nombre = txtHuesped.getText();
		fechaEntrada = txtFechaEntrada.getText();
		fechaSalida = txtFechaSalida.getText();
		total = txtTotal.getText();

		Imprimele imprimir = new Imprimele();
		imprimir.setFolio( this.folio );
		imprimir.setNumero( this.numero );
		imprimir.setNombre( this.nombre );
		imprimir.setFechaEntrada( this.fechaEntrada );
		imprimir.setFechaSalida( this.fechaSalida );
		imprimir.setTotal( this.total );

		/*imprimir.folio = this.folio;
		imprimir.numero = this.numero;
		imprimir.nombre = this.nombre;
		imprimir.fechaEntrada = this.fechaEntrada;
		imprimir.fechaSalida = this.fechaSalida;
		imprimir.total = this.total;*/
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
			{
				if ( "Nimbus".equals( info.getName() ) )
				{
					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
					break;
				}
			}
		}
		catch ( ClassNotFoundException ex )
		{
			java.util.logging.Logger.getLogger( VentanaHistorial.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( InstantiationException ex )
		{
			java.util.logging.Logger.getLogger( VentanaHistorial.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( IllegalAccessException ex )
		{
			java.util.logging.Logger.getLogger( VentanaHistorial.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( javax.swing.UnsupportedLookAndFeelException ex )
		{
			java.util.logging.Logger.getLogger( VentanaHistorial.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				new VentanaHistorial().setVisible( true );
			}

		} );
	}

	public String getFolio()
	{
		return folio;
	}

	public void setFolio( String folio )
	{
		this.folio = folio;
	}

	public String getNombre()
	{
		return nombre;
	}

	public void setNombre( String nombre )
	{
		this.nombre = nombre;
	}

	public String getNumero()
	{
		return numero;
	}

	public void setNumero( String numero )
	{
		this.numero = numero;
	}

	public String getFechaEntrada()
	{
		return fechaEntrada;
	}

	public void setFechaEntrada( String fechaEntrada )
	{
		this.fechaEntrada = fechaEntrada;
	}

	public String getFechaSalida()
	{
		return fechaSalida;
	}

	public void setFechaSalida( String fechaSalida )
	{
		this.fechaSalida = fechaSalida;
	}

	public String getTotal()
	{
		return total;
	}

	public void setTotal( String total )
	{
		this.total = total;
	}

	DefaultTableModel m;
	String folio, nombre, numero, fechaEntrada, fechaSalida, total;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrarSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblHistorialReservación;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtHuesped;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
