
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Casillas
 */
public class VentanaEmpleado extends javax.swing.JFrame
{

	/**
	 * Creates new form VentanaEmpleado
	 */
	public VentanaEmpleado()
	{
		initComponents();
		m = ( DefaultTableModel ) tblEmpleado.getModel();

		cargarTablaDesdeBD();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Buscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnEliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblAPaterno = new javax.swing.JLabel();
        txtAPaterno = new javax.swing.JTextField();
        lblAMaterno = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblDomicilio = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblTelefono1 = new javax.swing.JLabel();
        lblTelefono2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHorarioSalida = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/hotel-3.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 160, 100);

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1400, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleados");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 140, 170, 30);

        jToolBar1.setBackground(new java.awt.Color(0, 0, 153));
        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/diagnostico.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);
        jToolBar1.add(jSeparator1);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/escritor.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);
        jToolBar1.add(jSeparator2);

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/lupa-de-busqueda.png"))); // NOI18N
        Buscar.setText("Buscar");
        Buscar.setFocusable(false);
        Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Buscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(Buscar);
        jToolBar1.add(jSeparator3);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/usuario.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);
        jToolBar1.add(jSeparator4);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(10, 180, 824, 58);

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Id", "Nombre", "Apellido Paterno", "Apellido Materno", "Edad", "Domicilio", "Telefono", "Cargo ", "Entrada", "Salida"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblEmpleado.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleado);
        if (tblEmpleado.getColumnModel().getColumnCount() > 0)
        {
            tblEmpleado.getColumnModel().getColumn(0).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(1).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(2).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(3).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(4).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(5).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(6).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(7).setResizable(false);
            tblEmpleado.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 824, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 720);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTitulo.setText("Nuevo Empleado");
        jPanel2.add(lblTitulo);
        lblTitulo.setBounds(240, 10, 149, 25);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombre.setText("Nombre(s):");
        jPanel2.add(lblNombre);
        lblNombre.setBounds(50, 70, 90, 22);

        jSeparator5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 42, 808, 10);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre);
        txtNombre.setBounds(250, 60, 270, 40);

        lblAPaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAPaterno.setText("Apellido Paterno:");
        jPanel2.add(lblAPaterno);
        lblAPaterno.setBounds(50, 120, 134, 22);

        txtAPaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAPaterno.setEnabled(false);
        txtAPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtAPaternoKeyTyped(evt);
            }
        });
        jPanel2.add(txtAPaterno);
        txtAPaterno.setBounds(250, 110, 270, 40);

        lblAMaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAMaterno.setText("Apellido Materno: ");
        jPanel2.add(lblAMaterno);
        lblAMaterno.setBounds(50, 170, 144, 22);

        txtAMaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAMaterno.setEnabled(false);
        txtAMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtAMaternoKeyTyped(evt);
            }
        });
        jPanel2.add(txtAMaterno);
        txtAMaterno.setBounds(250, 160, 270, 40);

        lblEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEdad.setText("Edad:");
        jPanel2.add(lblEdad);
        lblEdad.setBounds(50, 220, 45, 22);

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEdad.setEnabled(false);
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel2.add(txtEdad);
        txtEdad.setBounds(250, 210, 270, 40);

        lblDomicilio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDomicilio.setText("Domicilio:");
        jPanel2.add(lblDomicilio);
        lblDomicilio.setBounds(50, 270, 110, 22);

        txtDomicilio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDomicilio.setEnabled(false);
        jPanel2.add(txtDomicilio);
        txtDomicilio.setBounds(250, 260, 270, 40);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefono.setText("Horario:");
        jPanel2.add(lblTelefono);
        lblTelefono.setBounds(50, 410, 100, 30);

        txtCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCargo.setEnabled(false);
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtCargoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCargo);
        txtCargo.setBounds(250, 360, 270, 40);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/multiplicar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(360, 490, 130, 40);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/agregar-usuario (2).png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);
        btnAgregar.setBounds(100, 490, 130, 40);

        lblTelefono1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefono1.setText("Télefono:");
        jPanel2.add(lblTelefono1);
        lblTelefono1.setBounds(50, 310, 100, 30);

        lblTelefono2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefono2.setText("Cargo:");
        jPanel2.add(lblTelefono2);
        lblTelefono2.setBounds(50, 360, 100, 30);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTelefono.setEnabled(false);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(250, 310, 270, 40);

        txtHorario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHorario.setEnabled(false);
        txtHorario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtHorarioKeyTyped(evt);
            }
        });
        jPanel2.add(txtHorario);
        txtHorario.setBounds(230, 410, 100, 40);

        jLabel3.setText("Entrada");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 420, 47, 16);

        jLabel4.setText("Salida");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(350, 420, 37, 16);

        txtHorarioSalida.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtHorarioSalida.setEnabled(false);
        jPanel2.add(txtHorarioSalida);
        txtHorarioSalida.setBounds(400, 410, 120, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(840, 60, 550, 660);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/boton-de-inicio.png"))); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addContainerGap(1299, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 730, 1400, 60);

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(830, 0, 570, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

	private void desbloquear()
	{
		txtNombre.setEnabled( true );
		txtNombre.requestFocus();
		txtAPaterno.setEnabled( true );
		txtAMaterno.setEnabled( true );
		txtEdad.setEnabled( true );
		txtDomicilio.setEnabled( true );
		txtTelefono.setEnabled( true );
		txtCargo.setEnabled( true );
		txtHorario.setEnabled( true );
		txtHorarioSalida.setEnabled( true );
	}

	private void bloquear()
	{
		txtNombre.setEnabled( false );
		txtAPaterno.setEnabled( false );
		txtAMaterno.setEnabled( false );
		txtEdad.setEnabled( false );
		txtDomicilio.setEnabled( false );
		txtTelefono.setEnabled( false );
		txtCargo.setEnabled( false );
		txtHorario.setEnabled( false );
		txtHorarioSalida.setEnabled( false );
	}

	private void limpiar()
	{
		txtNombre.setText( "" );
		txtAPaterno.setText( "" );
		txtAMaterno.setText( "" );
		txtEdad.setText( "" );
		txtDomicilio.setText( "" );
		txtTelefono.setText( "" );
		txtCargo.setText( "" );
		txtHorario.setText( "" );
		txtHorarioSalida.setText( "" );
	}
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

		desbloquear();
		btnAgregar.setEnabled( true );
		btnNuevo.setEnabled( false );
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		limpiar();
		bloquear();
		btnNuevo.setEnabled( true );
		btnAgregar.setEnabled( false );
		btnEditar.setEnabled( false );
		btnEliminar.setEnabled( false );
		m.setRowCount( 0 );
		cargarTablaDesdeBD();
    }//GEN-LAST:event_btnCancelarActionPerformed

	private void llenarTabla()
	{
		Object O[] = new Object[ 5 ];
		O[ 0 ] = txtNombre.getText();
		O[ 1 ] = txtAPaterno.getText();
		O[ 2 ] = txtAMaterno.getText();
		O[ 3 ] = txtCargo.getText();
		O[ 4 ] = txtHorario.getText();

		m.addRow( O );
	}
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

		if ( btnNuevo.isEnabled() == false && btnEditar.isEnabled() == true )

		{
			try
			{
				valida();
				validaEdad();
				validaTel();
				editar();
				m.setRowCount( 0 );
				cargarTablaDesdeBD();

				limpiar();
				bloquear();

				btnNuevo.setEnabled( true );
				btnAgregar.setEnabled( false );
				btnEliminar.setEnabled( false );
				btnEditar.setEnabled( false );

			}
			catch ( EmpleadoException e )
			{
				showMessageDialog( rootPane , e.getMessage() );
			}
		}
		else
		{
			try
			{
				valida();
				validaEdad();
				validaTel();
				insertar();
				m.setRowCount( 0 );
				cargarTablaDesdeBD();

				limpiar();
				bloquear();

				btnNuevo.setEnabled( true );
				btnAgregar.setEnabled( false );

			}
			catch ( EmpleadoException e )
			{
				showMessageDialog( rootPane , e.getMessage() );
			}
		}
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
		char e = evt.getKeyChar();
		if ( ( ( e < 'A' ) || ( e > 'Z' ) ) && ( ( e < 'a' ) || ( e > 'z' ) ) && ( e != ' ' ) )
		{
			evt.consume();
		}
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtAPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPaternoKeyTyped
		char e = evt.getKeyChar();
		if ( ( ( e < 'A' ) || ( e > 'Z' ) ) && ( ( e < 'a' ) || ( e > 'z' ) ) && ( e != ' ' ) )
		{
			evt.consume();
		}
    }//GEN-LAST:event_txtAPaternoKeyTyped

    private void txtAMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMaternoKeyTyped
		char e = evt.getKeyChar();
		if ( ( ( e < 'A' ) || ( e > 'Z' ) ) && ( ( e < 'a' ) || ( e > 'z' ) ) && ( e != ' ' ) )
		{
			evt.consume();
		}
    }//GEN-LAST:event_txtAMaternoKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
		char e = evt.getKeyChar();
		if ( ( ( e < '0' ) || ( e > '9' ) ) )
		{
			evt.consume();
		}
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyTyped

    }//GEN-LAST:event_txtCargoKeyTyped

    private void tblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadoMouseClicked
		btnNuevo.setEnabled( false );
		btnEditar.setEnabled( true );
		btnEliminar.setEnabled( true );

		txtNombre.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 1 ).toString() );
		txtAPaterno.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 2 ).toString() );
		txtAMaterno.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 3 ).toString() );
		txtEdad.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 4 ).toString() );
		txtDomicilio.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 5 ).toString() );
		txtTelefono.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 6 ).toString() );
		txtCargo.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 7 ).toString() );
		txtHorario.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 8 ).toString() );
		txtHorarioSalida.setText( tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 9 ).toString() );

		bloquear();

    }//GEN-LAST:event_tblEmpleadoMouseClicked

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
		char e = evt.getKeyChar();
		if ( ( ( e < '0' ) || ( e > '9' ) ) )
		{
			evt.consume();
		}
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtHorarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorarioKeyTyped
		// TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
		if ( javax.swing.JOptionPane.showConfirmDialog( this , "¿Desea eliminar este registro" , "Borrar!!!" , JOptionPane.YES_NO_OPTION ) == 0 )
		{
			String cad = "";
			Connection c = conexionBD();
			cad = "delete from Empleado where id = " + tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 0 ).toString() + ";";

			try
			{
				Statement stmt = c.createStatement();
				stmt.executeUpdate( cad );
				m.removeRow( tblEmpleado.getSelectedRow() );
				limpiar();
				btnEliminar.setEnabled( false );
				btnEditar.setEnabled( false );
				btnNuevo.setEnabled( true );

			}
			catch ( SQLException ex )
			{
				showMessageDialog( this , "Error al borrar" + ex.getMessage() );
			}
		}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
		Inicio inicio = new Inicio();
		inicio.setVisible( true );
		this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditarActionPerformed
    {//GEN-HEADEREND:event_btnEditarActionPerformed
		desbloquear();
		btnAgregar.setEnabled( true );

    }//GEN-LAST:event_btnEditarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BuscarActionPerformed
    {//GEN-HEADEREND:event_BuscarActionPerformed
		String cad = JOptionPane.showInputDialog( "Ingrese el id del empleado" );
		m.setRowCount( 0 );
		buscar( cad );
    }//GEN-LAST:event_BuscarActionPerformed

	private Connection conexionBD()
	{
		String url = "jdbc:mysql://localhost:3306/Hotel";
		System.out.println( "Conectando..." );

		Connection connection = null;

		try
		{
			connection = DriverManager.getConnection( url , "root" , "werick" );

			System.out.println( "Conectado a la base de datos " + "Hotel" + " !!" );

		}
		catch ( SQLException e )
		{
			System.out.println( "No se pudo conectar a la base de datos " + "Hotel" );
			System.out.println( e.getMessage() );
		}

		return connection;
	}

	private void agregar_a_tabla( int s1 , String s2 , String s3 , String s4 , int s5 , String s6 , String s7 , String s8 , String s9 , String s10 )
	{

		// aquí agregar las cadenas a la tabla
		Object O[] = new Object[ 10 ];
		O[ 0 ] = s1;
		O[ 1 ] = s2;
		O[ 2 ] = s3;
		O[ 3 ] = s4;
		O[ 4 ] = s5;
		O[ 5 ] = s6;
		O[ 6 ] = s7;
		O[ 7 ] = s8;
		O[ 8 ] = s9;
		O[ 9 ] = s10;

		m.addRow( O );

	}

	private void buscar( String cad )
	{
		String q = "select * from Empleado where id=" + cad + ";";

		Connection c = conexionBD();

		String prueba = "";

		int Id;
		String nombre;
		String apellidoPaterno;
		String apellidoMaterno;
		int edad;
		String domicilio;
		String telefono;
		String cargo;
		String horarioEntrada;
		String horarioSalida;

		try
		{

			Statement stmt = c.createStatement();
			stmt.execute( q );
			ResultSet rs = stmt.getResultSet();
			if ( rs != null )
			{
				while ( rs.next() )
				{
					Id = rs.getInt( "id" );
					nombre = rs.getString( "nombre" );
					apellidoPaterno = rs.getString( "apellidoPaterno" );
					apellidoMaterno = rs.getString( "apellidoMaterno" );
					edad = rs.getInt( "edad" );
					domicilio = rs.getString( "domicilio" );
					telefono = rs.getString( "telefono" );
					cargo = rs.getString( "cargo" );
					horarioEntrada = rs.getString( "horarioEntrada" );
					horarioSalida = rs.getString( "horarioSalida" );

					/*prueba += "(" + strNumero + "," + strTipo + "," + strDisponibilidad + ","
						+ strPrecio + ")\n";*/
					agregar_a_tabla( Id , nombre , apellidoPaterno , apellidoMaterno , edad , domicilio , telefono , cargo , horarioEntrada , horarioSalida );
				}
			}

			c.close(); // no dejar la conexión abierta

		}
		catch ( SQLException e )
		{
			System.out.println( "Error al cargar datos de la tabla " + "Hotel" );
			System.out.println( e.getMessage() );
		}

		System.out.println( q + "\n" + prueba );

	}

	private void cargarTablaDesdeBD()
	{
		String q = "select * from " + "Empleado" + ";";

		Connection c = conexionBD();

		String prueba = "";

		int Id;
		String nombre;
		String apellidoPaterno;
		String apellidoMaterno;
		int edad;
		String domicilio;
		String telefono;
		String cargo;
		String horarioEntrada;
		String horarioSalida;

		try
		{

			Statement stmt = c.createStatement();
			stmt.execute( q );
			ResultSet rs = stmt.getResultSet();
			if ( rs != null )
			{
				while ( rs.next() )
				{
					Id = rs.getInt( "id" );
					nombre = rs.getString( "nombre" );
					apellidoPaterno = rs.getString( "apellidoPaterno" );
					apellidoMaterno = rs.getString( "apellidoMaterno" );
					edad = rs.getInt( "edad" );
					domicilio = rs.getString( "domicilio" );
					telefono = rs.getString( "telefono" );
					cargo = rs.getString( "cargo" );
					horarioEntrada = rs.getString( "horarioEntrada" );
					horarioSalida = rs.getString( "horarioSalida" );

					/*prueba += "(" + strNumero + "," + strTipo + "," + strDisponibilidad + ","
						+ strPrecio + ")\n";*/
					agregar_a_tabla( Id , nombre , apellidoPaterno , apellidoMaterno , edad , domicilio , telefono , cargo , horarioEntrada , horarioSalida );
				}
			}

			c.close(); // no dejar la conexión abierta

		}
		catch ( SQLException e )
		{
			System.out.println( "Error al cargar datos de la tabla " + "Hotel" );
			System.out.println( e.getMessage() );
		}

		System.out.println( q + "\n" + prueba );

	}

	public void editar()
	{
		String nombre = txtNombre.getText();
		String apellidoPaterno = txtAPaterno.getText();
		String apellidoMaterno = txtAMaterno.getText();
		int edad = Integer.parseInt( txtEdad.getText() );
		String domicilio = txtDomicilio.getText();
		String telefono = txtTelefono.getText();
		String cargo = txtCargo.getText();
		String horarioEntrada = txtHorario.getText();
		String horarioSalida = txtHorarioSalida.getText();

		Connection c = conexionBD();
		String insert = "update Empleado set nombre=?,apellidoPaterno=?,apellidoMaterno=?,edad=?,domicilio=?,telefono=?,cargo=?,horarioEntrada=?,horarioSalida=? where id=" + tblEmpleado.getValueAt( tblEmpleado.getSelectedRow() , 0 ).toString();

		try
		{
			Statement stmt = c.createStatement();
			PreparedStatement ps;

			ps = c.prepareStatement( insert );
			ps.setString( 1 , nombre );
			ps.setString( 2 , apellidoPaterno );
			ps.setString( 3 , apellidoMaterno );
			ps.setInt( 4 , edad );
			ps.setString( 5 , domicilio );
			ps.setString( 6 , telefono );
			ps.setString( 7 , cargo );
			ps.setString( 8 , horarioEntrada );
			ps.setString( 9 , horarioSalida );

			ps.executeUpdate();

			c.close();
		}
		catch ( SQLException ex )
		{
			Logger.getLogger( VentanaReservacion.class.getName() ).log( Level.SEVERE , null , ex );

		}

	}

	public void insertar()
	{
		String nombre = txtNombre.getText();
		String apellidoPaterno = txtAPaterno.getText();
		String apellidoMaterno = txtAMaterno.getText();
		int edad = Integer.parseInt( txtEdad.getText() );
		String domicilio = txtDomicilio.getText();
		String telefono = txtTelefono.getText();
		String cargo = txtCargo.getText();
		String horarioEntrada = txtHorario.getText();
		String horarioSalida = txtHorarioSalida.getText();

		Connection c = conexionBD();
		String insert = "insert into Empleado (nombre,apellidoPaterno,apellidoMaterno,edad,domicilio,telefono,cargo,horarioEntrada,horarioSalida) values(?,?,?,?,?,?,?,?,?)";

		try
		{
			Statement stmt = c.createStatement();
			PreparedStatement ps;

			ps = c.prepareStatement( insert );
			ps.setString( 1 , nombre );
			ps.setString( 2 , apellidoPaterno );
			ps.setString( 3 , apellidoMaterno );
			ps.setInt( 4 , edad );
			ps.setString( 5 , domicilio );
			ps.setString( 6 , telefono );
			ps.setString( 7 , cargo );
			ps.setString( 8 , horarioEntrada );
			ps.setString( 9 , horarioSalida );

			ps.executeUpdate();

			c.close();
		}
		catch ( SQLException ex )
		{
			Logger.getLogger( VentanaReservacion.class.getName() ).log( Level.SEVERE , null , ex );

		}

	}

	private void valida() throws EmpleadoException
	{
		if ( txtNombre.getText().equals( "" ) )
		{
			txtNombre.requestFocus();
			throw new EmpleadoException( "Casilla Nombre sin llenar" );
		}
		if ( txtAPaterno.getText().equals( "" ) )
		{
			txtAPaterno.requestFocus();
			throw new EmpleadoException( "Casilla Apellido Paterno sin llenar" );
		}
		if ( txtAMaterno.getText().equals( "" ) )
		{
			txtAMaterno.requestFocus();
			throw new EmpleadoException( "Casilla Apellido Materno sin llenar" );
		}
		if ( txtEdad.getText().equals( "" ) )
		{
			txtEdad.requestFocus();
			throw new EmpleadoException( "Casilla Edad sin llenar" );
		}
		if ( txtDomicilio.getText().equals( "" ) )
		{
			txtDomicilio.requestFocus();
			throw new EmpleadoException( "Casilla Domicilio sin llenar" );
		}
		if ( txtTelefono.getText().equals( "" ) )
		{
			txtTelefono.requestFocus();
			throw new EmpleadoException( "Casilla Telefono sin llenar" );
		}
		if ( txtCargo.getText().equals( "" ) )
		{
			txtCargo.requestFocus();
			throw new EmpleadoException( "Casilla Cargo sin llenar" );
		}

	}

	private void validaEdad() throws EmpleadoException
	{
		int edad = Integer.parseInt( txtEdad.getText() );
		if ( edad < 18 || edad > 100 )
		{
			txtEdad.requestFocus();
			throw new EmpleadoException( "Edad No Valida" );
		}

	}

	private void validaTel() throws EmpleadoException
	{
		String tel = txtTelefono.getText();
		int a = tel.length();
		if ( a != 10 )
		{
			txtTelefono.requestFocus();
			throw new EmpleadoException( "Telefono No Valida (10 digitos)" );
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
			{
				if ( "Nimbus".equals( info.getName() ) )
				{
					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
					break;
				}
			}
		}
		catch ( ClassNotFoundException ex )
		{
			java.util.logging.Logger.getLogger( VentanaEmpleado.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( InstantiationException ex )
		{
			java.util.logging.Logger.getLogger( VentanaEmpleado.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( IllegalAccessException ex )
		{
			java.util.logging.Logger.getLogger( VentanaEmpleado.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		catch ( javax.swing.UnsupportedLookAndFeelException ex )
		{
			java.util.logging.Logger.getLogger( VentanaEmpleado.class.getName() ).log( java.util.logging.Level.SEVERE , null , ex );
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				new VentanaEmpleado().setVisible( true );
			}

		} );
	}

	private DefaultTableModel m;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAMaterno;
    private javax.swing.JLabel lblAPaterno;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtHorarioSalida;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
